create table vin_vehicles
(
    id                                                         int auto_increment primary key,
    last_refresh_date_time                                     datetime,
    vech_id                                                    varchar(200) not null,
    vehicles_vin                                               varchar(200),
    vehicles_registration_community                            varchar(200), -- "rejestracja-gmina"
    vehicles_registration_country                              varchar(200), -- "rejestracja-powiat"
    vehicles_registration_voivodeship                          varchar(200), -- "rejestracja-wojewodztwo"
    vehicles_date_last_registration_in_country                 varchar(200), -- "data-ostatniej-rejestracji-w-kraju"
    vehicles_date_first_registration                           varchar(200), -- "data-pierwszej-rejestracji"
    vehicles_date_first_registration_in_country                varchar(200), -- "data-pierwszej-rejestracji-w-kraju"
    vehicles_date_first_registration_abroad                    varchar(200), -- "data-pierwszej-rejestracji-za-granica"
    vehicles_date_data_input                                   varchar(200), -- "data-wprowadzenia-danych"
    vehicles_date_of_deregistration                            varchar(200), -- "data-wyrejestrowania-pojazdu"
    vehicles_allowed_package                                   int,          -- "dopuszczalna-ladownosc"
    vehicles_permissible_gross_weight                          int,          -- "dopuszczalna-masa-calkowita"
    vehicles_permissible_total_weight_of_vehicle_combinations  int,          -- "dopuszczalna-masa-calkowita-zespolu-pojazdow"
    vehicles_co2_emission_level                                int,          -- "poziom-emisji-co2"
    vehicles_co2_emission_level_first_fuel_alternative         int,          -- "poziom-emisji-co2-pierwsze-paliwo-alternatwne"
    vehicles_co2_emission_level_second_fuel_alternative        int,          -- "poziom-emisji-co2-drugie-paliwo-alternatwne"
    vehicles_category                                          varchar(200), -- "kategoria-pojazdu"
    vehicles_car_transport_institute_code                      varchar(200), -- "kod-instytutu-transportu-samochodowego"
    vehicles_code_kind_subgenus_destiny                        varchar(200), -- "kod-rodzaj-podrodzaj-przeznaczenie"
    vehicles_number_seats_total                                int,          -- "liczba-miejsc-ogolem"
    vehicles_number_of_seats                                   int,          -- "liczba-miejsc-siedzacych"
    vehicles_number_of_standing_places                         int,          -- "liczba-miejsc-stojacych"
    vehicles_number_of_axles                                   int,          -- "liczba-osi"
    vehicles_maximum_payload                                   int,          -- "maksymalna-ladownosc"
    vehicles_maximum_total_mass                                int,          -- "maksymalna-masa-calkowita"
    vehicles_max_total_weight_of_trailed_trailer_without_brake int,          -- "max-masa-calkowita-ciagnietej-przyczepy-bez-hamulca"
    vehicles_max_total_weight_trailer_without_brake            int,          -- "max-masa-calkowita-przyczepy-bez-hamulca"
    vehicles_max_net_power_of_engine_hybrid                    int,          -- "max-moc-netto-silnikow-pojazdu-hybrydowego"
    vehicles_maximum_track_width                               int,          -- "max-rozstaw-kol"
    vehicles_engine_net_power                                  int,          -- "moc-netto-silnika"
    vehicles_brand                                             varchar(200), -- "marka"
    vehicles_mass_of_ready_to_run                              int,          -- "masa-pojazdu-gotowego-do-jazdy"
    vehicles_own_mass                                          int,          -- "masa-wlasna"
    vehicles_min_track_width                                   int,          -- "min-rozstaw-kol"
    vehicles_model                                             varchar(200), -- "model"
    vehicles_allowable_axle_load                               int,          -- "dopuszczalny-nacisk-osi"
    vehicles_maximum_axle_weight                               int,          -- "maksymalny-nacisk-osi"
    vehicles_manufacturer_name                                 varchar(200), -- "nazwa-producenta"
    vehicles_origin                                            varchar(200), -- "pochodzenie-pojazdu"
    vehicles_subtype                                           varchar(200), -- "podrodzaj-pojazdu"
    vehicles_engine_displacement                               int,          -- "pojemnosc-skokowa-silnika"
    vehicles_destination                                       varchar(200), -- "przeznaczenie-pojazdu"
    vehicles_reason_for_deregistration_of_vehicle              varchar(200), -- "przyczyna-wyrejestrowania-pojazdu"
    vehicles_exhaust_emission_reduction                        int,          -- "redukcja-emisji-spalin"
    vehicles_kind_of_second_alternative_fuel                   varchar(200), -- "rodzaj-drugiego-paliwa-alternatywnego"
    vehicles_type_encoding_kind_subtype_destiny                varchar(200), -- "rodzaj-kodowania-rodzaj-podrodzaj-przeznaczenie"
    vehicles_type_of_fuel                                      varchar(200), -- "rodzaj-paliwa"
    vehicles_kind_of_first_alternative_fuel                    varchar(200), -- "rodzaj-pierwszego-paliwa-alternatywnego"
    vehicles_kind                                              varchar(200), -- "rodzaj-pojazdu"
    vehicles_nameplate_type                                    varchar(200), -- "rodzaj-tabliczki-znamionowej"
    vehicles_kind_of_suspensions                               varchar(200), -- "rodzaj-zwieszenia"
    vehicles_year_of_production                                varchar(200), -- "rok-produkcji"
    vehicles_wheel_base_steering_other_axles                   varchar(200), -- "rozstaw-kol-osi-kierowanej-pozostalych-osi"
    vehicles_owner_commune                                     varchar(200), -- "wlasciciel-gmina"
    vehicles_owner_district                                    varchar(200), -- "wlasciciel-powiat"
    vehicles_owner_voivodeship                                 varchar(200), -- "wlasciciel-wojewodztwo"
    vehicles_method_of_production                              varchar(200), -- "sposob-produkcji"
    vehicles_avg_spacing_col                                   int,          -- "avg-rozstaw-kol"
    vehicles_avg_fuel_consumption                              int,          -- "avg-zuzycie-paliwa"
    vehicles_motor_power_to_weight_ratio_motorcycles           int,          -- "stosunek-mocy-silnika-do-masy-wlasnej-motocykle"
    vehicles_type                                              varchar(200), -- "typ"
    vehicles_variant                                           varchar(200), -- "wariant"
    vehicles_version                                           varchar(200), -- "wersja"
    vehicles_equipment_and_type_of_radar_device                varchar(200), -- "wyposazenie-i-rodzaj-urzadzenia-radarowego"
    vehicles_steering_right_hand_side                          boolean,      -- "kierownica-po-prawej-stronie"
    vehicles_steering_right_side_originally                    boolean,      -- "kierownica-po-prawej-stronie-pierwotnie"
    vehicles_hook                                              boolean,      -- "hak"
    vehicles_catalyst_absorber                                 boolean,      -- "katalizator-pochlaniacz"
    vehicles_voivodeship_code                                  varchar(200), -- "wojewodztwo-kod"
    vehicles_owner_voivodeship_code                            varchar(200), -- "wlasciciel-wojewodztwo-kod"
    vehicle_vin                                                varchar(200),
    vehicle_registration_community                             varchar(200), -- "rejestracja-gmina"
    vehicle_registration_country                               varchar(200), -- "rejestracja-powiat"
    vehicle_registration_voivodeship                           varchar(200), -- "rejestracja-wojewodztwo"
    vehicle_date_last_registration_in_country                  varchar(200), -- "data-ostatniej-rejestracji-w-kraju"
    vehicle_date_first_registration                            varchar(200), -- "data-pierwszej-rejestracji"
    vehicle_date_first_registration_in_country                 varchar(200), -- "data-pierwszej-rejestracji-w-kraju"
    vehicle_date_first_registration_abroad                     varchar(200), -- "data-pierwszej-rejestracji-za-granica"
    vehicle_date_data_input                                    varchar(200), -- "data-wprowadzenia-danych"
    vehicle_date_of_deregistration                             varchar(200), -- "data-wyrejestrowania-pojazdu"
    vehicle_allowed_package                                    int,          -- "dopuszczalna-ladownosc"
    vehicle_permissible_gross_weight                           int,          -- "dopuszczalna-masa-calkowita"
    vehicle_permissible_total_weight_of_vehicle_combinations   int,          -- "dopuszczalna-masa-calkowita-zespolu-pojazdow"
    vehicle_co2_emission_level                                 int,          -- "poziom-emisji-co2"
    vehicle_co2_emission_level_first_fuel_alternative          int,          -- "poziom-emisji-co2-pierwsze-paliwo-alternatwne"
    vehicle_co2_emission_level_second_fuel_alternative         int,          -- "poziom-emisji-co2-drugie-paliwo-alternatwne"
    vehicle_category                                           varchar(200), -- "kategoria-pojazdu"
    vehicle_car_transport_institute_code                       varchar(200), -- "kod-instytutu-transportu-samochodowego"
    vehicle_code_kind_subgenus_destiny                         varchar(200), -- "kod-rodzaj-podrodzaj-przeznaczenie"
    vehicle_number_seats_total                                 int,          -- "liczba-miejsc-ogolem"
    vehicle_number_of_seats                                    int,          -- "liczba-miejsc-siedzacych"
    vehicle_number_of_standing_places                          int,          -- "liczba-miejsc-stojacych"
    vehicle_number_of_axles                                    int,          -- "liczba-osi"
    vehicle_maximum_payload                                    int,          -- "maksymalna-ladownosc"
    vehicle_maximum_total_mass                                 int,          -- "maksymalna-masa-calkowita"
    vehicle_max_total_weight_of_trailed_trailer_without_brake  int,          -- "max-masa-calkowita-ciagnietej-przyczepy-bez-hamulca"
    vehicle_max_total_weight_trailer_without_brake             int,          -- "max-masa-calkowita-przyczepy-bez-hamulca"
    vehicle_max_net_power_of_engine_hybrid                     int,          -- "max-moc-netto-silnikow-pojazdu-hybrydowego"
    vehicle_maximum_track_width                                int,          -- "max-rozstaw-kol"
    vehicle_engine_net_power                                   int,          -- "moc-netto-silnika"
    vehicle_brand                                              varchar(200), -- "marka"
    vehicle_mass_of_ready_to_run                               int,          -- "masa-pojazdu-gotowego-do-jazdy"
    vehicle_own_mass                                           int,          -- "masa-wlasna"
    vehicle_min_track_width                                    int,          -- "min-rozstaw-kol"
    vehicle_model                                              varchar(200), -- "model"
    vehicle_allowable_axle_load                                int,          -- "dopuszczalny-nacisk-osi"
    vehicle_maximum_axle_weight                                int,          -- "maksymalny-nacisk-osi"
    vehicle_manufacturer_name                                  varchar(200), -- "nazwa-producenta"
    vehicle_origin                                             varchar(200), -- "pochodzenie-pojazdu"
    vehicle_subtype                                            varchar(200), -- "podrodzaj-pojazdu"
    vehicle_engine_displacement                                int,          -- "pojemnosc-skokowa-silnika"
    vehicle_destination                                        varchar(200), -- "przeznaczenie-pojazdu"
    vehicle_reason_for_deregistration_of_vehicle               varchar(200), -- "przyczyna-wyrejestrowania-pojazdu"
    vehicle_exhaust_emission_reduction                         int,          -- "redukcja-emisji-spalin"
    vehicle_kind_of_second_alternative_fuel                    varchar(200), -- "rodzaj-drugiego-paliwa-alternatywnego"
    vehicle_type_encoding_kind_subtype_destiny                 varchar(200), -- "rodzaj-kodowania-rodzaj-podrodzaj-przeznaczenie"
    vehicle_type_of_fuel                                       varchar(200), -- "rodzaj-paliwa"
    vehicle_kind_of_first_alternative_fuel                     varchar(200), -- "rodzaj-pierwszego-paliwa-alternatywnego"
    vehicle_kind                                               varchar(200), -- "rodzaj-pojazdu"
    vehicle_nameplate_type                                     varchar(200), -- "rodzaj-tabliczki-znamionowej"
    vehicle_kind_of_suspensions                                varchar(200), -- "rodzaj-zwieszenia"
    vehicle_year_of_production                                 varchar(200), -- "rok-produkcji"
    vehicle_wheel_base_steering_other_axles                    varchar(200), -- "rozstaw-kol-osi-kierowanej-pozostalych-osi"
    vehicle_owner_commune                                      varchar(200), -- "wlasciciel-gmina"
    vehicle_owner_district                                     varchar(200), -- "wlasciciel-powiat"
    vehicle_owner_voivodeship                                  varchar(200), -- "wlasciciel-wojewodztwo"
    vehicle_method_of_production                               varchar(200), -- "sposob-produkcji"
    vehicle_avg_spacing_col                                    int,          -- "avg-rozstaw-kol"
    vehicle_avg_fuel_consumption                               int,          -- "avg-zuzycie-paliwa"
    vehicle_motor_power_to_weight_ratio_motorcycles            int,          -- "stosunek-mocy-silnika-do-masy-wlasnej-motocykle"
    vehicle_type                                               varchar(200), -- "typ"
    vehicle_variant                                            varchar(200), -- "wariant"
    vehicle_version                                            varchar(200), -- "wersja"
    vehicle_equipment_and_type_of_radar_device                 varchar(200), -- "wyposazenie-i-rodzaj-urzadzenia-radarowego"
    vehicle_steering_right_hand_side                           boolean,      -- "kierownica-po-prawej-stronie"
    vehicle_steering_right_side_originally                     boolean,      -- "kierownica-po-prawej-stronie-pierwotnie"
    vehicle_hook                                               boolean,      -- "hak"
    vehicle_catalyst_absorber                                  boolean,      -- "katalizator-pochlaniacz"
    vehicle_voivodeship_code                                   varchar(200), -- "wojewodztwo-kod"
    vehicle_owner_voivodeship_code                             varchar(200)  -- "wlasciciel-wojewodztwo-kod"
)
    COLLATE = 'utf8_general_ci'
    ENGINE = InnoDB
;


create table vin_vehicles_params
(
    id                          int auto_increment primary key,
    last_refresh_date_time      datetime,
    voivodeship_code            varchar(100) not null,
    date_from                   datetime     not null,
    date_to                     datetime     not null,
    page                        int,
    generating_params_date_time datetime
)
    COLLATE = 'utf8_general_ci'
    ENGINE = InnoDB
;