ALTER TABLE viewers ADD SESSION_ID_TEMPORARY varchar(100);
UPDATE viewers SET SESSION_ID_TEMPORARY = SESSION_ID WHERE SESSION_ID_TEMPORARY IS null;
ALTER TABLE viewers DROP SESSION_ID;
ALTER TABLE viewers CHANGE SESSION_ID_TEMPORARY SESSION_ID VARCHAR(100);
CREATE INDEX idx_session_id ON viewers(SESSION_ID);
