export interface Premise {
  id: number,
  type: string,
  number: number,
  floor: number,
  surfacePerSqMeter: number,
  pricePerSqMeter: number,
  totalPrice: number,
  numberOfRooms: number,
  technicalStatus: string,
  salesStatus: string,
  exposure: string,
  buildingId: number,
  garden: number,
  loggia: number,
  balcony: number,
  terrace: number,
}
